import { describe, it, expect } from "vitest"
import { validatePan, validateAadhaar, normalizeIndianPhone, generateOtp, aadhaarCheckDigit } from "../src/lib/validation"

describe("PAN validation", () => {
  it("accepts valid PAN format", () => {
    expect(validatePan("ABCDE1234F")).toBe(true)
    expect(validatePan("abcde1234f")).toBe(true) // case-insensitive
  })

  it("rejects malformed PAN", () => {
    expect(validatePan("ABCD1234F")).toBe(false)
    expect(validatePan("ABCDE12345")).toBe(false)
    expect(validatePan("1234512341")).toBe(false)
    expect(validatePan("")).toBe(false)
    expect(validatePan("ABCDE1234FF")).toBe(false)
  })
})

describe("Aadhaar validation (Verhoeff)", () => {
  it("accepts a checksum-valid Aadhaar generated by the same algorithm", () => {
    const base11 = "23456789012"
    const full = `${base11}${aadhaarCheckDigit(base11)}`
    expect(full).toHaveLength(12)
    expect(validateAadhaar(full)).toBe(true)
  })

  it("rejects wrong length and leading 0/1", () => {
    expect(validateAadhaar("123456789012")).toBe(false) // starts with 1
    expect(validateAadhaar("23456789012")).toBe(false) // 11 digits
    expect(validateAadhaar("")).toBe(false)
  })

  it("rejects corrupted check digit", () => {
    const base11 = "98765432109"
    const valid = `${base11}${aadhaarCheckDigit(base11)}`
    const badLast = valid.slice(0, 11) + ((Number(valid[11]) + 1) % 10)
    expect(validateAadhaar(valid)).toBe(true)
    expect(validateAadhaar(badLast)).toBe(false)
  })

  it("ignores spaces and dashes", () => {
    const base11 = "34567890123"
    const full = `${base11}${aadhaarCheckDigit(base11)}`
    const spaced = `${full.slice(0, 4)} ${full.slice(4, 8)} ${full.slice(8)}`
    expect(validateAadhaar(spaced)).toBe(true)
  })
})

describe("Indian phone normalization", () => {
  it("accepts plain 10-digit numbers starting 6-9", () => {
    expect(normalizeIndianPhone("9876543210")).toBe("9876543210")
    expect(normalizeIndianPhone("6123456789")).toBe("6123456789")
  })

  it("strips +91 / 91 / 0 prefixes and formatting", () => {
    expect(normalizeIndianPhone("+919876543210")).toBe("9876543210")
    expect(normalizeIndianPhone("919876543210")).toBe("9876543210")
    expect(normalizeIndianPhone("09876543210")).toBe("9876543210")
    expect(normalizeIndianPhone("+91 98765 43210")).toBe("9876543210")
  })

  it("rejects invalid Indian mobiles", () => {
    expect(normalizeIndianPhone("1234567890")).toBeNull() // must start 6-9
    expect(normalizeIndianPhone("98765432")).toBeNull() // too short
    expect(normalizeIndianPhone("abcdefghij")).toBeNull()
  })
})

describe("OTP generation", () => {
  it("produces a 6-digit numeric code", () => {
    for (let i = 0; i < 50; i++) {
      const otp = generateOtp()
      expect(otp).toMatch(/^\d{6}$/)
    }
  })
})